name: taskit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  bottom_navy_bar: ^6.1.0
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  horizontal_calendar: ^1.1.2
  lucide_icons_flutter: ^1.2.5
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: poppins
      fonts:
        - asset: lib/Fonts/Poppins-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
